<?php
    return array(
        "create-user" => "User/Register",
        "login-user" => "User/SignIn",
        "update-user" => "User/EditData",
        "update-image" => "User/EditImage",
        "email/send/verify" => "User/EmailSendVerify",
        "email/verify.{1,}" => "User/EmailVerify",
        "validate" => "User/Validate",
        "sign-out" => "User/SignOut",
        "country" => "Location/Country",
        "region[?id=0-9]{0,}" => "Location/Region",
        "city[?id=0-9]{0,}" => "Location/City",
        "register" => "Site/Register",
        "sign-in" => "Site/SignIn",
        "cabinet" => "Site/Cabinet",
        "test" => "Site/Test",
         "" => "Site/SignIn",
        ".{1,}" => "Site/Error404",
    );